backend:
  name: git-gateway
  branch: main

media_folder: "images/blog" # Where your blog images will be saved
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog" # Where your blog text files will stay
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "SEO Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}